services:
  descarga:
    build:
      context: .
      dockerfile: docker/downloader/Dockerfile
    container_name: etl_descarga
    env_file: .env
    volumes:
      - .:/app
      - ${USERPROFILE}/.config/earthengine:/root/.config/earthengine
    environment:
      - PYTHONUNBUFFERED=1

  limpieza:
    build:
      context: .
      dockerfile: docker/cleaning/Dockerfile.limpieza
    container_name: etl_limpieza
    env_file: .env
    depends_on:
      descarga:
        condition: service_completed_successfully
    volumes:
      - .:/app
      - ${USERPROFILE}/.config/earthengine:/root/.config/earthengine
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python3", "/app/Proyecto/etl/main_limpieza.py"]

  mysql_server:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASS}"]
      interval: 3s
      timeout: 5s
      retries: 15

  carga_mysql:
    build:
      context: .
      dockerfile: docker/db_loader/Dockerfile.db
    container_name: etl_carga_db
    env_file: .env
    depends_on:
      mysql_server:
        condition: service_healthy
      limpieza:
        condition: service_completed_successfully
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "Proyecto/main_dbconnection.py"]

volumes:
  mysql_data: