FROM spark:3.5.1-python3

USER root

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3-pip build-essential gcc g++ \
    gdal-bin libgdal-dev libproj-dev libgeos-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
COPY constraints.txt .

RUN python3 -m pip install --upgrade pip setuptools wheel && \
    python3 -m pip install --no-cache-dir -r requirements.txt -c constraints.txt

COPY Proyecto/ /app/Proyecto/
COPY Proyecto/etl/Spark2/ /app/Spark2/
COPY data/ /app/data/
COPY municipios_es.geojson /app/municipios_es.geojson
COPY docker/cleaning/log4j2.properties /opt/spark/conf/log4j2.properties

RUN mkdir -p /app/data/clean

CMD ["python3", "/app/Proyecto/etl/main_limpieza.py"]