FROM python:3.12-slim
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      build-essential gcc g++ gdal-bin libgdal-dev libproj-dev libgeos-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
COPY constraints.txt .
RUN pip install --no-cache-dir -r requirements.txt -c constraints.txt

COPY Proyecto/ /app/Proyecto/
# ESTA ES LA LÍNEA QUE HARÁ QUE EL BUILD NO TARDE 0 SEGUNDOS:
COPY municipios_es.geojson /app/municipios_es.geojson

RUN mkdir -p /app/data
CMD ["python", "Proyecto/etl/main_limpieza.py"]